### ISSUE TITLE
Mby some new feature?

### ISSUE THREAD

**Issue by WapoX** [EgoPvP/scambuster#1]
Doing like scam buster rn but where u can report people who use/has an executer for FiveM Modding?

Good or bad idea?

**Comment by NoobKeksTV** [comment]
for modding / cheating / reseller / leaker on FiveM i can recoomend "vVarden"
they collect people IN cheating, leaking, reselling fivm discord servers and you can ban or kick them from your server.
their database is like oveer 200k banned members or something?
https://warden.isitleaked.com/
